### PR TITLE
added Canadian groundwater 1991 standard with definitions and vocab

### PR DESCRIPTION
**Pull request by denevers**
New reference documents + my comment document (not relevant anymore - should go in issues)

### CODE REVIEW

**Comment by sgrellet** [comment]
@denevers : thanks. Do you have online references as well ? could be added there : https://github.com/opengeospatial/boreholeie/wiki/Relevant-Materials

**Comment by denevers** [comment]
Nah.. it's a 1991 document we scanned 15 years ago.  There a no other digital version other than this one.
You will recognise the content as the basis of GWML construction package

**Comment by sgrellet** [comment]
Ok. I am on the vocabulary spreadsheet right now and re-re-discovered that there is no conceptual equivalent in GWML2 to the logical construction package... we may need to do this for BhML

**Comment by denevers** [comment]
We will be facing the same issue of scoping.  What parts of construction are "universal".  What part are domain specific. Maybe the BhML part is totally abstract ("BhConstructionElement" that have a position in the hole and that's it)

**Comment by sgrellet** [comment]
Not a bad plan (thanks for controlling my entropy :) )

**Comment by denevers** [comment]
I will reuse this expression

**Pull request merged**
